version: '3'

#1-> docker-compose up -d
#2-> docker exec -it web bash
services:
  backend_trsale:
    build:
      context: .
      dockerfile: dockerfile.dev      
    container_name: backend_trsale
    networks:
      - node-network
    volumes:
      - .:/app
    tty: true
    ports:
      - "5000:5000"
      - "5001:5001"
  
networks:
  node-network:
    driver: bridge