// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRSale.DataBase.Company;

#nullable disable

namespace TRSale.DataBase.Company.Migrations
{
    [DbContext(typeof(TRSaleCompanyContext))]
    [Migration("20220616020022_Vr01")]
    partial class Vr01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TRSale.Domain.Company.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryMotherId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryMotherId")
                        .IsUnique();

                    b.ToTable("Category", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8");
                });

            modelBuilder.Entity("TRSale.Domain.Company.Entities.Category", b =>
                {
                    b.HasOne("TRSale.Domain.Company.Entities.Category", "CategoryMother")
                        .WithOne()
                        .HasForeignKey("TRSale.Domain.Company.Entities.Category", "CategoryMotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryMother");
                });
#pragma warning restore 612, 618
        }
    }
}
